export const products = [
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
  { name: "a", price: 12, desc: "a letter" },
];
